### ISSUE TITLE
Can't start leofs_manager

### ISSUE THREAD

**Issue by Abdelwaheb-Hnaien** [leo-project/leofs#1036]
Hi, 
I'd like to report two issues that I encountered with LeoFS recently: 
The first one is related  to LeoFS v.1.4.0, I followed exactly the same installation steps mentioned in the official documentation and everything seems to be fine but when I come to run the following command **systemctl start leofs-manager-master leofs-manager-slave leofs-gateway leofs-storage** 
I get : 
`Job for leofs-manager-master.service failed because the control process exited with error code. See "systemctl status leofs-manager-master.service" and "journalctl -xe" for details`
This is the output of **systemctl status leofs-manager-master.service** command : 

```
leofs-manager-master.service - LeoFS master management node
   Loaded: loaded (/usr/lib/systemd/system/leofs-manager-master.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-04-29 10:49:22 WEST; 13s ago
  Process: 11344 ExecStop=/usr/local/leofs/current/leo_manager_0/bin/leo_manager stop (code=exited, status=127)
  Process: 10287 ExecStart=/usr/local/leofs/current/leo_manager_0/bin/leo_manager foreground_start (code=exited, status=1/FAILURE)
 Main PID: 10287 (code=exited, status=1/FAILURE)

Apr 29 10:49:22 192.168.0.115 systemd[1]: Failed to start LeoFS master management node.
Apr 29 10:49:22 192.168.0.115 systemd[1]: Unit leofs-manager-master.service entered failed state.
Apr 29 10:49:22 192.168.0.115 systemd[1]: leofs-manager-master.service failed
```
I tried the manual installation in two different environments, a Ubuntu VM machine on a Mac and another machine running CentOS 7. Each time I get exactly the same problem.
When I try to install older version of leoFS(v 1.3.8) I dont get this problem and I can run 'leofs-adm status' successefully.

The second issue is when I try to build a LeoFS (v 1.3.8) image from a Dockerfile.
Here is the Dockerfile content : 
```
# Dockerfile
FROM ubuntu:16.04 

RUN apt-get update && apt-get install wget lsb-release apt-utils -y

RUN wget https://github.com/leo-project/leofs/releases/download/1.4.0/leofs_1.4.0-1_erl-19.3_ubuntu-16.04_amd64.deb && chmod +x leofs_1.4.0-1_erl-19.3_ubuntu-16.04_amd64.deb

RUN sudo dpkg -i leofs_1.4.0-1_erl-19.3_ubuntu-16.04_amd64.deb && apt-get install -f

RUN sudo systemctl start leofs-manager-master leofs-manager-slave leofs-gateway leofs-storage

Expose 8080
``` 
when I run `docker build .` it stucks in **Step 4/6 : RUN dpkg -i leofs_1.3.8-1_erl-19.3_ubuntu-16.04_amd64.deb** and I get : 

```
adduser: Warning: The home directory `/usr/local/leofs' does not belong to the user you are currently creating.
Created symlink /etc/systemd/system/sockets.target.wants/leofs-epmd.socket, pointing to /lib/systemd/system/leofs-epmd.socket.                                
Failed to connect to bus: No such file or directory                                                                                                           
dpkg: error processing package leofs (--install):                                                                                                             
 subprocess installed post-installation script returned error exit status 1                                                                                   
Errors were encountered while processing:                                                                                                                     
 leofs                                                                                                                                                        
The command '/bin/sh -c dpkg -i leofs_1.3.8-1_erl-19.3_ubuntu-16.04_amd64.deb' returned a non-zero code: 1
```

I think docker execute commands with the `root` user and in this step it tries to access **/usr/local/leofs**  directory which belong to **leofs** user maybe.

My question is what prevents leofs_manager from starting ? and I'm wondering if anyone had previously made a docker file for building LeoFS image, or what shall I add to the Dockerfile to fix this. 

Thank you

**Comment by vstax** [comment]
@Abdelwaheb-Hnaien I'm sorry that I can't provide you with fully working solution. However, I wanted to note a few things that cause your current problem.

```
RUN sudo systemctl start leofs-manager-master leofs-manager-slave leofs-gateway leofs-storage
```
This won't work; you are trying to start LeoFS nodes using systemd, but systemd itself is not running inside your docker container! Additionally, even if you had systemd running, this command (`systemctl start`) would exit as soon as all LeoFS nodes start, and since it's your last RUN instruction, container will exit after that, crashing all the nodes. Definitely not something that you want.

I can offer a few options for you:

1. Learn how to properly start systemd inside container; start systemd, then start LeoFS using systemctl, then execute some waiting process which won't return. All in all, I can't recommend this way: running systemd inside container might be tricky, it probably requires quite a bit of docker knowledge or some good guide to do this; running LeoFS under systemd in container wasn't tested, there might be some problems with that as well. Also, for multiple reasons this isn't recommended way to use docker containers anyway.
2. Instead of using docker containers, use something else, like virtual machine. If you want to use containers, use ones designed for running full OS image with init, services and everything else like LXC or OpenVZ - not docker. In this case, you will have a proper OS running inside container or VM, where you can start services using systemd. I recommend this solution, because it will properly stop LeoFS node when stopping the container or VM.
3. Use docker the way it's supposed to be; create one container per node (one for each manager, each gateway and each storage), and start foreground process (without systemd) in each one. I recommend using launch script with "foreground_start" option, like `/usr/local/leofs/current/leo_manager_0/bin/leo_manager foreground_start`. Please note that you won't get any launch dependencies this way, the docker might start leo_storage first, for example, which will crash in the absence of leo_manager. This is expected, so you should either set container policy to auto-restart for all LeoFS containers or use something on top of docker which will do that (e.g. in kubernetes installation).

That said, launching is only a half of the problem; the other is how to stop LeoFS nodes properly. Right now there might be some problems with that when LeoFS is running in docker (I might be wrong here); please don't think of running LeoFS installation in production before making sure that nodes stop the way they're supposed to. Which is why I recommend the solution 2, which will kind of work properly right away; solutions 1 and 3 might require some work and testing. [Solution involving bash script that traps signals and executes command](https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86) should work for configuring a proper node shutdown with "docker stop" in solution 3. I have no idea how to accomplish anything similar in the solution 1...


```
Failed to connect to bus: No such file or directory                                                                                                           
```

This (and following) errors are because there is no systemd running inside container. They are expected, but should only be relevant for cases when trying to use systemd services after that (which you did, and thus nodes weren't able to start because "epmd" service couldn't start - naturally, since there is no service manager!). Current package for Ubuntu 16.04 kind of expects that it's being installed on system running systemd, which is not true for container configuration that you're using. Maybe this should improved, not sure; or maybe using a package for 16.04 is not a good idea for the containers right now.

Regarding the first problem, please provide output from `journalctl -xe -u leofs-manager-master` command and LeoFS info & error logs.

**Comment by mocchira** [comment]
@Abdelwaheb-Hnaien I think @vstax answered your question and asked you some info to solve your problem however there has been no responses from you so I'll close this issue.

Please reopen this issue and answer the asking from @vstax if you still have some problem.

FWIW for your second problem, we are going to provide official docker images for each component and helm chart for k8s deployment through https://github.com/leo-project/leofs/issues/1048 so once those come out, you'll be able to deploy LeoFS on docker(or k8s) easily more than ever before.

**Comment by mocchira** [comment]
@Abdelwaheb-Hnaien Regarding the first problem, we found the problem that the packages published on github were built by OTP **without systemd enabled** so it failed to start any components due to epmd not listening to sockets from systemd. 

Now we have just updated the latest(1.4.1) packages at

- https://github.com/leo-project/leofs/releases/download/1.4.1/leofs-1.4.1-1.el7.x86_64.rpm for CentOS/7
- https://github.com/leo-project/leofs/releases/download/1.4.1/leofs_1.4.1-1_ubuntu-16.04_amd64.deb for Ubuntu 16.04

Please try those out if you would still have interest.
Sorry for the inconvenience.
