### ISSUE TITLE
How to make leofs storage support streaming media ?

### ISSUE THREAD

**Issue by FunnyRyan** [leo-project/leofs#1096]
How to make leofs storage support streaming media,
 I want to use it as a backend storage for video sites

tips:
S3 Gateway
supoot MP4 at lest
HTML5 Player

**Comment by FunnyRyan** [comment]
Thank you guys

**Comment by FunnyRyan** [comment]
another problem was.....when i using command "leofs-adm create-user myuserID"
there was error message below:
/usr/local/bin/leofs-adm: line 71: lsb_release: command not found
/usr/local/bin/leofs-adm: line 72: lsb_release: command not found

dose anybody know why ?

**Comment by mocchira** [comment]
> How to make leofs storage support streaming media,
I want to use it as a backend storage for video sites

> tips:
S3 Gateway
supoot MP4 at lest
HTML5 Player

Yes you can with LeoFS >= 1.3.8. (The current stable is 1.4.2)
Actually there were another user trying to watch video files stored in LeoFS through the video tag (HTML5 Player) at https://groups.google.com/forum/#!topic/leoproject_leofs/wOiid2kR5c4

However I'd strongly recommend you put some reverse proxy software in front of LeoFS because LeoFS has not been designed to be placed in DMZ.

> /usr/local/bin/leofs-adm: line 71: lsb_release: command not found
/usr/local/bin/leofs-adm: line 72: lsb_release: command not found
> dose anybody know why ?

Run "sudo apt install lsb-release" if you're on debian/ubuntu or
Run "sudo yum install redhat-lsb-core" if you're on redhat/centos to have lsb_release installed in your system.

**Comment by FunnyRyan** [comment]
thank u  :>

**Comment by FunnyRyan** [comment]
I have built a single machine for leofs
It works, I bind Endpoint, and can upload or download files via  DragonDisk.
But i can't access files through the 80 port using direct link like this: http://testbucket.leofs.mydomain.com/test.jpg
Test.jpg exists in the bucket, I can download or delete it via DragonDisk.

dose anybody know why ? 

thank u guys

**Comment by FunnyRyan** [comment]
the testbucket's ACL was public-read, is it right ?

**Comment by mocchira** [comment]
> But i can't access files through the 80 port using direct link like this: http://testbucket.leofs.mydomain.com/test.jpg

If you run LeoGateway with the protocol set to s3 (default) at https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/priv/leo_gateway.conf#L48-L49 then HTTP access need the authentication header defined in S3 protocol spec.
That being said, you need to set protocol to rest or set the ACL to public-read|public-read-write.

**Comment by mocchira** [comment]
> the testbucket's ACL was public-read, is it right ?

Yes that should work.

**Comment by FunnyRyan** [comment]
Thank you very much. Some  cloud  i have used before need to be token verified. I think this is the problem, I will go see

**Comment by FunnyRyan** [comment]
excuse me
How does leofs achieve token protection?

The last question has been resolved
thank you very much

**Comment by mocchira** [comment]
> The last question has been resolved

@FunnyRyan Great to hear that then I'll close this issue. (Please reopen the issue or file another issue if you face another problem)
