### ISSUE TITLE
How does leofs achieve token protection?

### ISSUE THREAD

**Issue by FunnyRyan** [leo-project/leofs#1097]
How does leofs use tokens to protect files?

**Comment by mocchira** [comment]
LeoFS protect files by implementing AWS S3 Authentication in accordance with its spec defined at https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html.

So in order to understand "How does leofs use tokens to protect files", I think you'd need to read the above spec.

Please feel free to ask me again if I misunderstand your question.

**Comment by mocchira** [comment]
I'll close this issue as it's already answered and no replies for a long time.
