### ISSUE TITLE
How to deal with different names but the same files?

### ISSUE THREAD

**Issue by FunnyRyan** [leo-project/leofs#1106]
I think this is a very important functional requirement.

How to deal with different names but the same files uploading by different user or myself ? 

I have testing it...but it was re-uploaded it ....

I suggest to add the feature of md5 to stop duplicate file uploads, and record different names for different user in database ,

**Comment by mocchira** [comment]
Let me clarify your question.

> How to deal with different names but the same files uploading by different user or myself ?

For example, let's say
We have a file A and upload it into

- bucket/path/to/file/A
- bucket2/path/to/file/A

then How LeoFS deal with those two files is just having the same content at each name. This is the current spec. In a future version, we may implement Deduplication as described at https://github.com/leo-project/leofs#version-2. Until the Dedup comes out, I'd recommend you to implement the logic to avoid uploading duplicated files in some application layer as you described at the below comment

> I suggest to add the feature of md5 to stop duplicate file uploads, and record different names for different user in database ,

Also it might be helpful to use a file system having the dedup functionality (like ZFS) in order to reduce the used space on disk.

**Comment by mocchira** [comment]
I'll close this issue as it's already answered and no replies for a long time. please reopen if you have more questions about this topic.
