### ISSUE TITLE
[Question] Debian support

### ISSUE THREAD

**Issue by asphytotalxtc** [leo-project/leofs#1184]
Hi Guys,

We're about to go production with our LeoFS cluster however our standard deployment environments are based on Debian 9. I see you guys only provide packages for Centos/Ubuntu, and we've successfully installed the Ubuntu deb without issues, but I wanted to ask if doing this could result in any future issues relates to OS updates etc?

Do you guys do any testing against Debian at all? I see the package dependencies are rather modest with nothing that looks like a red flag but just wanted to ask if you guys had any insider knowledge or experience with this setup?

Many thanks in advance :)

Dan

**Comment by mocchira** [comment]
Unfortunately we haven't deployed LeoFS with Debian on our production environments, however I've heard some community users were using LeoFS on debian and AFAIK I haven't heard any trouble from them.

Only one thing I found going through our documentation is
https://leo-project.net/leofs/docs/faq/administration/#why-doesnt-leofs-adm-respond-to-a-command-like-leofs-adm-status

This issue was reported by our community users using LeoFS on debian9.

Anyway, feel free to file any issues if you face some trouble :)

**Comment by asphytotalxtc** [comment]
Ah thanks for the info @mocchira! Very helpful, we'll take those thoughts on board and make a decision :)
