### ISSUE TITLE
[leo_storage][mdc] Replication DELETE messages coudn't be consumed properly when the target objects already have been compacted

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#345]
When the target objects already have been compacted(physically removed by compaction) at a local cluster,
leo_sync_remote_cluster:compare_metadata/1 function doesn't work intentionally, 
so being executed [this block](https://github.com/leo-project/leo_storage/blob/develop/src/leo_sync_remote_cluster.erl#L247).
As a result, an invalid replication message could be generated.

**Comment by yosukehara** [comment]
Thank you for your report. I've considered this issue then reached the solution as below.

When A deletion object does not exist in the local cluster, the metadata's comparison process ignores abandon comparing the metadata between clusters because the local node has already executed data-compaction or auto-compaction. 

#### Processing Flow
1. Delete A
2. Sync A between clusters w/mdc-replication
3. Send A to the remote cluster
4. Remove A w/data-compaction > "not found"
5. Check the metadata between the local-cluster and the remote-cluster
    * if the same metadata then respond OK
    * if "not found" then ignore comparison process
    * if find a new "A" then GoTo 2: *Sync A' between clusters w/mdc-replication*
