### ISSUE TITLE
[1.2.11][leo_storage] Auto Compaction tend to be executed on the same node

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#396]
Even if there are other nodes to be compacted.
leo_storage_watchdog_sub:is_candidate_1 need to check all nodes whether compaction is needed or not even if MaxNumOfNodes is set to  a lower value.

**Comment by yosukehara** [comment]
We took [a benchmark of LeoFS v1.2.12-dev2](https://github.com/leo-project/notes/tree/1655ac138ddf9b2d16c38076a672f9ef6e4c9851/leofs/benchmark/leofs/recover_with_front/20150708_recover_node_1.2.12-dev2). We've recognized we fixed this issue but we will more check this issue with some tests.

**Comment by yosukehara** [comment]
I've arranged the benchmark results (CPU's chart) as below. So I've recognized interval between auto-compaction need to add a few seconds - 30-60sec is ideal because ``leo_storage`` executes switching processing from an old AVS to a new AVS.
 
![auto-compaction-benchmark-result-20150708-2 001](https://cloud.githubusercontent.com/assets/148770/8566972/bb305d7c-259c-11e5-92c9-9593271cdfc1.jpg)

**Comment by PatelParas** [comment]
this situation don't occur every time. it happens occasionally. If i need further information then i will contact you. Thank you.
