### ISSUE TITLE
Where to get an information about manager recovery

### ISSUE THREAD

**Issue by feedbee** [leo-project/leofs#512]
What should administrator do when manager nodes are broken?

Case 1: slave is broken. Will it be enough to create new slave manager, configure and start it?

Case 2: master is broken. What should admin do? Just to create, configure and start new master is not enough, cluster will not restore - tested.

And great thanks for this tool!

**Comment by yosukehara** [comment]
@feedbee I've answered your question as below, and I've recognized we need to publish a documentation of manager recovery. We also need to improve the way of manager recovery because that is not easy for LeoFS' administrators.

## Procedure of manager recovery
### Case 1: Recovery of a manager-master/manager-slave (not takeover)

- Stop both the manager-master and the manager-slave to avoid inconsistency of the data

```bash
$ leo_manager_<NUM>/bin/leo_manager stop
```

- Move `mnesia-files` which is under `work/mnesia/127.0.0.1` to another directory (backup)

```bash
$ mv leo_manager_1/work/mnesia/127.0.0.1/* <another-directory>
```

- Recover manager-master: 
    - Copy `mnesia-files` from the manager-slave to the manager-master _(not new one)_
- Recover manager-slave:
    - Copy `mnesia-files` from the manager-master to the manager-slave _(not new one)_

```bash
$ cp <mnesia-files> leo_manager_<NUM>/work/mnesia/127.0.0.1/*
```

- Restart both the manager-master and the manager-slave

```bash
$ leo_manager_<NUM>/bin/leo_manager start
```

### Case 2: Launch a new manager-master/slave instead of a collapsed node (takeover)

- Export the mnesia-files with `leofs-adm dump-mnesia-data` command, which is output at a specified node, manager-master or manager-slave

```bash
## for manager-master
$ leofs-adm dump-mnesia-data <absolute-path>

## for manager-slave
$ leofs-adm dump-mnesia-data -p <port (default:10011)> <absolute-path>
```

- Stop both the manager-manager and the manager-slave

```bash
$ leo_manager_<NUM>/bin/leo_manager stop
```

- Move `mnesia-files` which is under `work/mnesia/127.0.0.1` to another directory (backup)

```bash
$ mv leo_manager_<NUM>/work/mnesia/127.0.0.1/* <another-directory>
```

- Update the configuration of `manager.partner` to be able to communicate between manager-master and manager-slave.

```ini
## Partner of manager's alias
manager.partner = manager_<NUM>@<IP>
```

- Restart both manager-master and manager-slave

```bash
$ leo_manager_<NUM>/bin/leo_manager start
```

- Import the mnesia-data from the back-up file

```bash
$ leofs-adm load-mnesia-data <absolute-path>
```

- Update the manager nodes to be able to communicate with the storage and the gateway nodes

```bash
$ leofs-adm update-managers manager_0@127.0.0.1 manager_2@127.0.0.1
OK
```

**Comment by feedbee** [comment]
Thank you for response. **In version 1.3.0 `dump-mnesia-data` and `load-mnesia-data` commands are absent. Command `backup-mnesia` does not accept port to use it with slave.** So currently I wasn't able to test manager-master takeover recovery using file coping and `leofs-adm update-managers`.

I have test environment and want to reproduce manager-master takeover. I get 3 vm's up:
1) manager-master, storage
2) manager-slave, storage
3) gateway, storage

Let vm #1 to be broken. We lost it with it's data. So I have to install new vm with new manager-master and new storage. I have no questions about storage, node detaching and attaching is clear and my tests was completed successful. But manager-master recovery is still unattainable.

If we will get correct manual for this recovery, it will be very useful for all users because they will be able to google this page.

Thanks again.

**Comment by yosukehara** [comment]
@feedbee 

> In version 1.3.0 dump-mnesia-data and load-mnesia-data commands are absent. Command backup-mnesia does not accept port to use it with slave. So currently I wasn't able to test manager-master takeover recovery using file coping and leofs-adm update-managers.

I've found errors in [my previous comment](https://github.com/leo-project/leofs/issues/512#issuecomment-260248866), so corrected it as below:

- Export data-files with `leo_manager` command

```bash
## for manager-master
$ leo_manager_<NUM>/bin/leo_manager dump-mnesia-data <absolute-path>

## for manager-slave
$ leo_manager_<NUM>/bin/leo_manager dump-mnesia-data -p <port (default:10011)> <absolute-path>
```

- Import the data-files from the back-up file

```bash
$ leo_manager_<NUM>/bin/leo_manager load-mnesia-data <absolute-path>
```

You can see [the procedure of manager recovery](https://github.com/leo-project/leofs/issues/512#issuecomment-260248866) which was modified correctly.

**Comment by feedbee** [comment]
Trying to make backup **at manager-slave**:

```
root@node-2:~# /usr/local/leofs/1.3.0/leo_manager_1/bin/leo_manager dump-mnesia-data -p 10011 /root/b
Usage: leo_manager dump-mnesia-data <absolute-path>
```

If I omit the port option, nothing will be exported:
```
root@node-2:~# /usr/local/leofs/1.3.0/leo_manager_1/bin/leo_manager dump-mnesia-data /root/b/
root@node-2:~# ls -al /root/b/
total 8
drwxr-xr-x 2 root root 4096 Nov 14 12:12 .
drwx------ 6 root root 4096 Nov 14 12:19 ..
```

**At manager-master** situation is the same:

```
root@node-1:~# /usr/local/leofs/1.3.0/leo_manager_0/bin/leo_manager dump-mnesia-data /root/b/
root@node-1:~# ls -al /root/b/
total 8
drwxr-xr-x 2 root root 4096 Nov 18 10:53 .
drwx------ 6 root root 4096 Nov 18 10:53 ..
```

**Comment by yosukehara** [comment]
`leo_manager` is able to output a dump file to a directory which writting is previous permitted as below:

### Check leo_manager process
```bash
$ ps aux | grep beam
yosuke   15537  4.9  0.9 5636852 80984 pts/6   Ssl+ 10:02   0:01 
        /home/yosuke/dev/projects/leo-project/leofs-1.3.0/package/leo_manager_0/erts-7.3.1.2/bin/beam.smp -A 32 -K true -P 1048576 -- -root /home/yosuke/dev/projects/leo-project/leofs-1.3.0/package/leo_manager_0 -progname leo_manager -- -home /home/yosuke -- -boot /home/yosuke/dev/projects/leo-project/leofs-1.3.0/package/leo_manager_0/releases/1/leo_manager -mode embedded -config /home/yosuke/dev/projects/leo-project/leofs-1.3.0/package/leo_manager_0/etc/app.config -config ./snmp/snmpa_manager_0/leo_manager_snmp -smp enable -setcookie 401321b4 -name manager_0@127.0.0.1 -- console start
yosuke   15880  4.6  0.9 5761896 76768 pts/19  Ssl+ 10:02   0:01 
        /home/yosuke/dev/projects/leo-project/leofs-1.3.0/package/leo_manager_1/erts-7.3.1.2/bin/beam.smp -A 32 -K true -P 1048576 -- -root /home/yosuke/dev/projects/leo-project/leofs-1.3.0/package/leo_manager_1 -progname leo_manager -- -home /home/yosuke -- -boot /home/yosuke/dev/projects/leo-project/leofs-1.3.0/package/leo_manager_1/releases/1/leo_manager -mode embedded -config /home/yosuke/dev/projects/leo-project/leofs-1.3.0/package/leo_manager_1/etc/app.config -config ./snmp/snmpa_manager_1/leo_manager_snmp -hidden -smp enable -setcookie 401321b4 -name manager_1@127.0.0.1 -- console start

...
```

### Check a distination directory
```bash
drwxrwxr-x  2 yosuke yosuke 4096 Nov 21 10:05 tmp
```

### Execute `leo_manager dump-mnesia-data <absolute-path>`
```bash
$ ./package/leo_manager_0/bin/leo_manager dump-mnesia-data /home/yosuke/tmp/mgr_0.dump

$ cd /home/yosuke/dev/tmp
$ ls -la
-rw-rw-r--  1 yosuke yosuke 47410 Nov 21 10:05 mgr_0.dump
```

**Comment by feedbee** [comment]
@yosukehara, great thank you! I was trying to pass directory to <absolute-path>, but now I see that file path must be passed. So, master-manager replacement procedure have been successfully passed. One remark is that

```
## for manager-slave
$ leo_manager_<NUM>/bin/leo_manager dump-mnesia-data -p <port (default:10011)> <absolute-path>
```

does not require port, and the command does not support port option. It must be:

```
## for manager-slave
$ leo_manager_<NUM>/bin/leo_manager dump-mnesia-data <absolute-path>
```

**Comment by Argentum88** [comment]
Why on "not takeover" manager recovery you copy mnesia files from healthy manager, but on "takeover" manager recovery you use dump-mnesia-data?

These two methods are not interchangeable?

**Comment by yosukehara** [comment]
@Argentum88 I'll check again those procedures, and then describe the detail.

**Comment by vstax** [comment]
While trying to follow the "Case 2 (takeover)" from https://github.com/leo-project/leofs/issues/512#issuecomment-260248866, I had lots of strange problems until I realized that I need to remove contents of "mnesia" directory on **both** servers at once, not just on the one that's undergoing takeover procedure. I think it would be better if guide did show that you need to do it on both manager and slave in all cases, because current guide looks a bit like you're supposed to do it only on server where IP is being changed.

Currently:
```
$ mv leo_manager_<NUM>/work/mnesia/127.0.0.1/* <another-directory>
```

Better to have something like that:
```
$ mv leo_manager_0/work/mnesia/127.0.0.1/* <another-directory-1>
$ mv leo_manager_1/work/mnesia/127.0.0.1/* <another-directory-2>
```
explicitly showing that you need to do it on both nodes.

It's probably the same for "load-mnesia" command below that, I think (not 100% sure but that's how I did it) that you're supposed to execute it both on master and slave.

**Comment by mocchira** [comment]
Since the document has been available on the official doc at https://leo-project.net/leofs/docs/admin/system_admin/leo_manager/ , I'll close the issue.

Please reopen the issue if you find something to be fixed on the page.
