### ISSUE TITLE
[leo_storage][read-repair] don't work when metadata is valid but avs is broken

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#543]
because the current impl only check the metadata managed by leo_backend_db using head.
https://github.com/leo-project/leo_storage/blob/1.3.0/src/leo_storage_read_repairer.erl#L84-L87

we may also need to at least fetch the header in avs and compare that to its correspondig metadata locally and if not match then report that as a invalid to other nodes.

**Comment by mocchira** [comment]
To cover the cases when getting the content itself corrupted for some reason(hardware failure, software bug etc),
We need to retrieve the whole data block and calculate the checksum and compare that to the checksum of others.

**Comment by mocchira** [comment]
WIP.

memo:

- Call get_fun with IsForcedCheck := true when handling read_repair
  - https://github.com/leo-project/leofs/blob/1.3.6/apps/leo_storage/src/leo_storage_handler_object.erl#L283-L313
- Handle the return value {error, invalid_object}
  - https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_haystack.erl#L545
- and what should be done next?
  - invalidate the corresponding object/metadata and repair(correct_redundancies) through leo_mq or ..?

**Comment by mocchira** [comment]
It turned out that simply implementing this feature causes leo_storage to consume much Disk I/O especially on read-intensive workload more than ever as it forces each leo_storage to retrieve the whole body stored in AVS and calculate the md5 based on that in case handling read-repair.

So I'd like to propose introducing a new configuration that enables users to specify whether turning on this complete strict check or not in leo_storage.conf
- default: turn off to maintain the backward compatibility in terms of performance for existing users who expect leofs to outperform other products (like using leofs as part of HPC)

@yosukehara @windkit @vstax what do you think?

**Comment by yosukehara** [comment]
@mocchira 

> a new configuration that enables users to specify whether turning on this complete strict check or not in leo_storage.conf
> default: turn off to maintain the backward compatibility in terms of performance for existing users who expect leofs to outperform other products (like using leofs as part of HPC)

I agree with your propose. We will need to publish its documentation at the same time of v1.4.0 release:

- [Configuration section](https://leo-project.net/leofs/docs/admin/settings/leo_storage/)
- [Consistency section](https://leo-project.net/leofs/docs/admin/settings/cluster/#consistency-level)

**Comment by vstax** [comment]
@mocchira 
If there is serious performance degradation and new option is needed, is it possible to add some commentary about (expected) degradation to option commentary? E.g.
```
## Enabling this option can degrade performance by 5-30% (depending on load type) by
## introducing extra IO during reads. Please evaluate the impact before enabling this
## on production cluster.
```

Btw, I kind of forgot when exactly read-repair is executed - is it what happens to two secondary nodes with N=3 and R=1 (because is_strict_check=True covers data checking for primary node)? Or it's about something else?

Anyhow this covers the case where data in AVS is incorrect (distorted); but was another important case with missing AVS file. E.g. when having `metadata` directories on SSD and storing AVS files themselves on HDDs and losing one of HDDs with AVS files, currently it's required to wipe corresponding metadata before getting both read-repairs and effective result from repair-node. IIRC this issue was supposed to cover that case as well?

Is it possible to also have more lightweight version of this check that (knowing the offset of object in AVS file from metadata) simply checks if corresponding AVS file actually has required header at that offset, thus allowing to go on without wiping metadata? Maybe that one will have low enough impact to be enabled by default?

Besides losing AVS file completely (well, it's more like truncating it because it will be recreated), I can think of one more case when this feature is needed. If hard lockup or reboot happens (without syncing buffers), the file can be truncated. Metadata itself will be synced but truncation of AVS file will occur on offset that either depends on write buffer (I have no idea how writes are done to AVS, always by some buffer like 64K? And what about objects smaller than buffer size?) or on some other factors, e.g. XFS can truncate files a bit more than expected at some conditions.

Assuming that metadata thinks that object is written but AVS file is truncated in the middle of that object's body (or middle or end of previous object, without mention of this one at all), is it possible to recover consistency of possibly broken objects on this node automatically or with repair-node? I understand that full implementation of this feature should fix such case, I'm asking here if more lightweight version of it (that just checks header) can be enough to deal with unclean reboot that results in truncated AVS file.

The idea is that it might be possible to have this option enabled to some "lightweight" check all the time and run data scrubs from time to time (when implemented in the future) for offline recovery of objects that hare broken data.

**Comment by mocchira** [comment]
@vstax

> If there is serious performance degradation and new option is needed, is it possible to add some commentary about (expected) degradation to option commentary? E.g.

Sure.

> Btw, I kind of forgot when exactly read-repair is executed - is it what happens to two secondary nodes with N=3 and R=1 (because is_strict_check=True covers data checking for primary node)? Or it's about something else?

read-repair always get executed on ANY GET request regardless of how N, R are configured. and now since HEAD (which touches only metadata) is used for read-repair to compare the checksum between replicas, this issue have existed.

> Anyhow this covers the case where data in AVS is incorrect (distorted); but was another important case with missing AVS file. E.g. when having metadata directories on SSD and storing AVS files themselves on HDDs and losing one of HDDs with AVS files, currently it's required to wipe corresponding metadata before getting both read-repairs and effective result from repair-node. IIRC this issue was supposed to cover that case as well?

Yes should be covered with this fix.

> Is it possible to also have more lightweight version of this check that (knowing the offset of object in AVS file from metadata) simply checks if corresponding AVS file actually has required header at that offset, thus allowing to go on without wiping metadata? Maybe that one will have low enough impact to be enabled by default?

Good point. I think it's possible and make sense to have more light weight version and make it default once the benchmarks show us no non-negligible performance degradation.

> Assuming that metadata thinks that object is written but AVS file is truncated in the middle of that object's body (or middle or end of previous object, without mention of this one at all), is it possible to recover consistency of possibly broken objects on this node automatically or with repair-node? I understand that full implementation of this feature should fix such case, I'm asking here if more lightweight version of it (that just checks header) can be enough to deal with unclean reboot that results in truncated AVS file.

I think it's possible to deal with truncated AVS files by light weight version implementing
- seek to the offset
- retrieved only the header and check the correctness
- seek to the next object offset calculated by the header 
- retrieved only the header and check the correctness (this operation should fail if the former object is truncated on AVS) 

needless to say, this is not perfect as there can be the case that the tail part of the object happen to be same with the header of the next one however taking the length of the header (128byte) into account, the possibility of collision can be similar to md5 at best (when the distribution is as good as md5).

That being said, IMO it can be enough in practice. thoughts?

**Comment by windkit** [comment]
To me, this raises the need of a data scrubbing tools/daemon so user can check data integrity
Now it is only checked at read (on primary replica only?)

**Comment by vstax** [comment]
@mocchira 
If you don't mind explaining in a bit more detail... About read-repair, is my understanding correct that before this change: HEAD now checks only metadata, while with it it's supposed to check data in AVS file as well (whether data will always be checked or not and strictness of check is under discussion).
As for GET request, let's suppose N=3, R=2 settings (and all nodes working), so when gateway tries to execute GET for full object: with is_strict_check=False, it obviously checks metadata and that data is complete (of correct size), since it needs to retrieve that data at least on the node that is processing the GET request. Does this happens on just one node or on two nodes? And the third one, if I understand you correctly, gets HEAD request instead and only checks metadata?
And with is_strict_check=True, at least one node (or two?) does through check of data and compares it to checksum in metadata as well.

There are queries specifying range as well, do they change anything? (obviously for at least is_strict_check=True a full object still has to be read...)

> I think it's possible to deal with truncated AVS files by light weight version implementing

Yes something like that. Or, alternatively, even without seek and check for the next object: just check this object's header in AVS file and that's it. In case even more performance is needed to keep this option enabled by default. This will cover "empty AVS" cause (well, since AVS gets filled as well, there is theoretically a collision problem similar to the one that you mention but chances are so low it obviously can be ignored). For "truncated AVS" cause, it will miss inconsistency of only a single object (the one that was truncated); if AVS was truncated in such way so that multiple objects in the end were lost, this check will correctly detect inconsistencies of all objects besides the one that was truncated since their offsets will point into some other data now. And that lone object can be left broken till it's actually read (and fixed then because of size inconsistency), till compaction is executed (which should detect that next header isn't at the correct place and mark this object as broken.. I think? No idea) or till data scrub is executed. IMHO this can be a fine compromise and it saves on seek in AVS file which can be expensive in case of HDD.

**Comment by mocchira** [comment]
@windkit Yea already filed here: https://github.com/leo-project/leofs/issues/574

**Comment by mocchira** [comment]
@vstax 

> As for GET request, let's suppose N=3, R=2 settings (and all nodes working), so when gateway tries to execute GET for full object: with is_strict_check=False, it obviously checks metadata and that data is complete (of correct size), since it needs to retrieve that data at least on the node that is processing the GET request. Does this happens on just one node or on two nodes? And the third one, if I understand you correctly, gets HEAD request instead and only checks metadata?

Happened only one on the primary. the others (secondary and third) will be received the HEAD from the primary, retrieve the metadata from backend_db on each and then send it back to the primary.

What R almost means is waiting for (R-1) HEAD replies from others in order to reply to the client.

> And with is_strict_check=True, at least one node (or two?) does through check of data and compares it to checksum in metadata as well.

Same as above. the only difference is calculating MD5 based on the body retrieved from AVS and comparing it to one on the metadata will happen on the primary.

> There are queries specifying range as well, do they change anything? (obviously for at least is_strict_check=True a full object still has to be read...)

Nothing should be changed however I've found the current IMPL is problematic as it doesn't check the md5 at all even if is_strict_check is set to true. I will file it as another issue later.

> Yes something like that. Or, alternatively, even without seek and check for the next object: just check this object's header in AVS file and that's it. In case even more performance is needed to keep this option enabled by default. This will cover "empty AVS" cause (well, since AVS gets filled as well, there is theoretically a collision problem similar to the one that you mention but chances are so low it obviously can be ignored). For "truncated AVS" cause, it will miss inconsistency of only a single object (the one that was truncated); if AVS was truncated in such way so that multiple objects in the end were lost, this check will correctly detect inconsistencies of all objects besides the one that was truncated since their offsets will point into some other data now. And that lone object can be left broken till it's actually read (and fixed then because of size inconsistency), till compaction is executed (which should detect that next header isn't at the correct place and mark this object as broken.. I think? No idea) or till data scrub is executed. IMHO this can be a fine compromise and it saves on seek in AVS file which can be expensive in case of HDD.

Got your point. I will look into further with some prototyping and will decide the final spec.

**Comment by mocchira** [comment]
filed https://github.com/leo-project/leofs/issues/947 for the problem - GET with Range header and is_strict_check = true.

**Comment by mocchira** [comment]
Now the corresponding PR got merged on develop.
TODO:
- [ ] benchmark rebalance/recover on RIT environment > @windkit

**Comment by windkit** [comment]
@mocchira Noted. going to run the benchmark :)

**Comment by windkit** [comment]
![recover-node-strict](https://user-images.githubusercontent.com/360884/35308775-9ccf2060-00ec-11e8-9c2e-8ed01727ad18.png)

1. Load image f4m data set
2. Stop storage node `S1@192.168.100.37`
3. Remove AVS files on storage node `S1@192.168.100.37`
4. Start storage node `S1@192.168.100.37`
5. `leofs-adm recover-node S1@192.168.100.37`

Here is the result of current develop branch with `is_strict_check=true`, the total number of object and total size went up but a subsequent compaction would fix the number

**Comment by mocchira** [comment]
@windkit Sorry for the long delay. Looks good to me.
@vstax The final spec has been decided to what you suggested "Yes something like that. Or, alternatively, even without seek and check for the next object: just check this object's header in AVS file and that's it." This works well in almost cases through our tests.
