### ISSUE TITLE
[leo_object_storage] get fsync configurable

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#573]
Suggested in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/leoproject_leofs/QsxY2wNWhYg/YV2Xlx2AFgAJ

IMHO +1 to implement.
and providing with several ways to control when fsync is called would be also desirable.
- Call periodically at a background process
- Call after finishing to put an object

**Comment by mocchira** [comment]
WIP.

**Comment by yosukehara** [comment]
I've confirmed this issue was fixed by [PR: Fix leo_object_storage for 1.3.3 #8](https://github.com/leo-project/leo_object_storage/pull/8), and I've added configurations for LeoFS v1.3.3 and leo_object_storage v1.3.1:
- https://github.com/leo-project/leofs/commit/c47b2c305cef292c51f6ab8bdc4f5fde3ebb6ab1
