### ISSUE TITLE
leofs compile on erlang 19 fail, because cuttlefish not support 19.

### ISSUE THREAD

**Issue by getong** [leo-project/leofs#724]
I compile the 1.3.4, and the failed msg is 
```
ERROR: OTP release 19 does not match required regex R16|17|18
ERROR: compile failed while processing /home/user/leofs-1.3.4/deps/getopt: rebar_abort
```
I also find the cuttlefish on `hex.pm` fix this problem, but this requires rebar3, not suitable for us now.
The repo is on `https://github.com/tsloughter/cuttlefish`, the develop branch.
Hope this will help.

**Comment by yosukehara** [comment]
As you can see, a dependency tree of `leo_storage` which is related to `cuttlefish` is as below.
`bitcask` depends on `cuttlefish v2.0.11`. However, this method is a bit tricky. We'll consider sending PR to fix this root cause.

- [leofs/apps/leo_storage](https://github.com/leo-project/leofs/tree/master/apps/leo_storage)
    - [leo_object_storage](https://github.com/leo-project/leo_object_storage), [leo_mq](https://github.com/leo-project/leo_mq)
        - [leo_backend_db](https://github.com/leo-project/leo_backend_db)
            - [bitcask](https://github.com/basho/bitcask)
                - [cuttlefish v2.0.11](https://github.com/basho/cuttlefish/releases/tag/2.0.11)


If you'd like to now build LeoFS with **Erlang/OTP 19.x**, you need to execute `replace_otp_vsn.sh`, which modify cuttlefish's `require_otp_vsn` in `rebar.config`.

- Execute it

```bash
$ cd leofs
$ ./replace_otp_vsn.sh
```

- Confirm cuttlefish's rebar.config

```diff
$ cd deps/cuttlefish/
$ git diff
diff --git a/rebar.config b/rebar.config
index 4173ca9..7999fdb 100644
--- a/rebar.config
+++ b/rebar.config
@@ -1,4 +1,4 @@
-{require_otp_vsn, "R16|17|18"}.
+{require_otp_vsn, "R16B*|17|18|19"}.

 {erl_opts, [warnings_as_errors, {parse_transform, lager_transform}, debug_info, warn_untyped_record]}.

```
