### ISSUE TITLE
[leo_storage] PR 802 break listing objects

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#821]
https://github.com/leo-project/leofs/pull/802 should be reverted as it cause listing objects to return a wrong result.

### Why
Now narrowing down the result of listing objects to MaxKeys has been conducted on leo_gateway at here: https://github.com/leo-project/leofs/blob/1.3.5-rc4/apps/leo_gateway/src/leo_gateway_s3_api.erl#L2144-L2201 so fetch_by_key with MaxKeys should never be used on leo_storage.

**Comment by windkit** [comment]
I agree the PR breaks the result now, but I don't agree it should never be used.

We are doing unnecessary long listing when max_key is not used and it causes problem of listing bucket in system with tons of object

The problem is also due to the code at leo_object_storage_api:fetch_by_key/3
https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_api.erl#L285

The sub list results came from multiple metadata server are not sorted, when we use the sublist to crop off the list, the marker for subsequent would be incorrect

===== Illustration =====

Metadata1: obj0, obj13 <- sorted
Metddata2: obj1, obj2  <- sorted

Combined List: [obj0, obj13, obj1, ojb2] <- not sorted
Cropped List: [obj0, obj13] <- not sorted
Correct List: [obj0, obj1]

The cropped list is incorrect and therefore the next marker is incorrect

To solve the problem we can first sort the combined list
```
Reply = lists:sort(lists:reverse(lists:flatten(Ret))),
              Or 
Reply = lists:sublist(ordsets:from_list(lists:flatten(List)), MaxKeys)
```

Or merge it, so order is maintained (n-way merge though)

This problem did not show up when the max_key is undefined (i.e. not passed to leo_object_storage_api)

**Comment by mocchira** [comment]
Yes. this fix is for short-term. the permanent fix should be carefully discussed on the other place so please file the new issue @windkit with the above your comment.

**Comment by mocchira** [comment]
revert PR here: https://github.com/leo-project/leofs/pull/822
