### ISSUE TITLE
Old Cluster cannot join cluster from 1.3.3, incompatible system_conf sent

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#914]
leofs-adm  join-cluster manager_0@10.39.20.29:13075 manager_1@10.39.20.25:13076 
[ERROR] Could not connect

**Comment by windkit** [comment]
This is caused by the change on `system_conf_2` to `system_conf_3` introduced at `1.3.3`

In `1.3.2` manager, `leo_manager_console` sends requests to `1.3.7` manager with `system_conf_2` record but `1.3.7` manager expects `system_conf_3` in `leo_manager_api:join_cluster/2`

At `1.3.2` manager
```
(leo_manager_0@192.168.100.36)7> recon_trace:calls({leo_rpc, '_', fun(_) -> return_trace() end}, 1000, [{scope, local}]).
10:7:16.801064 <0.649.0> leo_rpc:call('leo_manager_1@192.168.100.35:13076', leo_manager_api, join_cluster, [['leo_manager_0@192.168.100.36','leo_manager_1@192.168.100.36'],
 {system_conf_2,1,leofs_1,dc_1,3,1,2,2,128,1,0,2}])
```

At `1.3.7` manager
```
(leo_manager_0@192.168.100.35)9> recon_trace:calls({leo_manager_api, join_cluster, fun(_) -> return_trace() end}, 1000).
1
9:52:59.342161 <0.11574.0> leo_manager_api:join_cluster(['leo_manager_0@192.168.100.36','leo_manager_1@192.168.100.36'], {system_conf_2,1,leofs_1,dc_1,3,1,2,2,128,1,0,2})
```

We need the same mechanism as `metadata` for `system_conf`

**Comment by windkit** [comment]
Tested with `1.3.2.1`
