### ISSUE TITLE
 Is the stable version of leofs now? The production environment is recommended to use that version

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#929]

**Comment by yosukehara** [comment]
I recommend you use LeoFS v1.3.7 but If you find issues that you care about in [v1.3.8](https://github.com/leo-project/leofs/milestone/71), you'd better wait until v1.3.8 is released, which will be provided at mid of this month.

**Comment by xingxing9688** [comment]
If the version is upgraded, what's the good solution?

**Comment by yosukehara** [comment]
If you follow [the procedure of the system migration](https://leo-project.net/leofs/docs/admin/system_admin/migration/), you can upgrade your LeoFS _(from v1.3.7 to v1.3.8)_.

**Comment by mocchira** [comment]
@yosukehara 

For the record.
IIRC (correct me if you @xingxing9688 find something wrong) since @xingxing9688 run LeoFS with the strong consistent setting (N=3, R=W=D=3) on purpose, the rolling upgrade procedure we  would recommend doesn't work for him (down time will occur during upgrading each storage). The only way to achieve upgrades without downtime is creating a new cluster and doing  multi-dc replication (MDCR) as he actually tried. Noting this info on somewhere in the doc might be helpful for other users.

**Comment by yosukehara** [comment]
@mocchira We need to write a document about that until delivering v1.3.8. I'll file it as another issue.
